CREATE TABLE IF NOT EXISTS USERS (
    USER_ID SERIAL PRIMARY KEY,
    USER_NAME VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS STATIONS (
    STATION_ID SERIAL PRIMARY KEY,
    STATION_NAME VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOKINGS (
    BOOKING_ID SERIAL PRIMARY KEY,
    USER_ID INTEGER NOT NULL REFERENCES USERS(USER_ID),
    STATION_ID INTEGER NOT NULL REFERENCES STATIONS(STATION_ID),
    BOOKING_DATE TIMESTAMP NOT NULL
);


INSERT INTO USERS (USER_ID, USER_NAME) VALUES
(1, 'Test user');

INSERT INTO STATIONS (STATION_ID, STATION_NAME) VALUES
(1, 'Station One'),
(2, 'Station Two'),
(3, 'Station Four :)');

INSERT INTO BOOKINGS (BOOKING_ID, USER_ID, STATION_ID, BOOKING_DATE) VALUES
(9999, 1, 2, '2025-01-01 12:00:00');